<a href="https://colab.research.google.com/github/olumayowaadeniyi68-arch/AVCAD-EXERCISE/blob/main/Exercise3_Univariate_Visualizations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load dataset
df = pd.read_csv("EFIplus_medit.csv")

# Show

In [ ]:
# Show column names
print(df.columns)

Index(['Site_code;Latitude;Longitude;Country;Catchment_name;Galiza;Subsample;Calib_EFI_Medit;Calib_connect;Calib_hydrol;Calib_morphol;Calib_wqual;Geomorph1;Geomorph2;Geomorph3;Water_source_type;Flow_regime;Altitude;Geological_typology;Actual_river_slope;Natural_sediment;Elevation_mean_catch;prec_ann_catch;temp_ann;temp_jan;temp_jul;Barriers_catchment_down;Barriers_river_segment_up;Barriers_river_segment_down;Barriers_number_river_segment_up;Barriers_number_river_segment_down;Barriers_distance_river_segment_up;Barriers_distance_river_segment_down;Impoundment;Hydropeaking;Water_abstraction;Hydro_mod;Temperature_impact;Velocity_increase;Reservoir_flushing;Sedimentation;Channelisation;Cross_sec;Instream_habitat;Riparian_vegetation;Embankment;Floodprotection;Floodplain;Toxic_substances;Acidification;Water_quality_index;Eutrophication;Organic_pollution;Organic_siltation;Sum of Run1_number_all;Total_sp;Abramis brama;Achondrostoma arcasii;Achondrostoma occidentale;Achondrostoma oligolepis;Acipenser naccarii;Alburnoides bipunctatus;Alburnus albidus;Alburnus alburnus;Alosa alosa;Alosa fallax;Ameiurus melas;Anaecypris hispanica;Anguilla anguilla;Atherina boyeri;Australoheros facetus;Barbatula barbatula;Barbatula quignardi;Barbus barbus;Barbus bocagei;Barbus comizo;Barbus graellsii;Barbus haasi;Barbus meridionalis;Barbus microcephalus;Barbus plebejus;Barbus sclateri;Barbus tyberinus;Blicca bjoerkna;Carassius auratus;Carassius carassius;Chelon labrosus;Chondrostoma genei;Chondrostoma nasus;Chondrostoma soetta;Chondrostoma toxostoma;Cobitis calderoni;Cobitis paludica;Cobitis taenia;Cottus gobio;Cottus hispaniolensis;Cyprinus carpio;Dicentrarchus labrax;Esox lucius;Gambusia affinis;Gambusia holbrooki;Gasterosteus aculeatus;Gasterosteus gymnurus;Gobio gobio;Gobio lozanoi;Gymnocephalus cernuus;Hypophthalmichthys molitrix;Iberochondrostoma almacai;Iberochondrostoma lemmingii;Iberochondrostoma lusitanicum;Lampetra fluviatilis;Lampetra planeri;Lepomis gibbosus;Leuciscus cephalus;Leuciscus leuciscus;Leuciscus lucumonis;Leuciscus souffia;Liza aurata;Liza ramada;Luciobarbus guiraonis;Micropterus salmoides;Mugil cephalus;Oncorhynchus mykiss;Pachychilon pictum;Padogobius martensii;Padogobius nigricans;Parachondrostoma arrigonis;Parachondrostoma miegii;Parachondrostoma turiense;Perca fluviatilis;Petromyzon marinus;Phoxinus bigerri;Phoxinus phoxinus;Platichthys flesus;Pseudochondrostoma duriense;Pseudochondrostoma polylepis;Pseudochondrostoma willkommii;Pseudorasbora parva;Rhodeus amarus;Rutilus aula;Rutilus rubilio;Rutilus rutilus;Salaria fluviatilis;Salmo salar;Salmo trutta fario;Salmo trutta macrostigma;Salvelinus fontinalis;Sander lucioperca;Scardinius erythrophthalmus;Silurus glanis;Squalius alburnoides;Squalius aradensis;Squalius carolitertii;Squalius laietanus;Squalius malacitanus;Squalius pyrenaicus;Squalius torgalensis;Thymallus thymallus;Tinca tinca;Zingel asper;Squalius sp;Barbatula sp;Phoxinus sp;Iberochondrostoma_sp'], dtype='object')

In [ ]:
# Find top 4 catchments
top_catchments = df['Catchment_name'].value_counts().head(4)

# Show results
print(top_catchments)

Catchment_name
Ebro            736
Galiza-Norte    709
Minho           707
Tejo            509
Name: count, dtype: int64

In [ ]:
# Store top 4 catchment names
top4 = top_catchments.index

print(top4)

Index(['Ebro', 'Galiza-Norte', 'Minho', 'Tejo'], dtype='object', name='Catchment_name')

In [ ]:
# Create filtered dataset using top 4 catchments
filtered_df = df[df['Catchment_name'].isin(top4)]

# Preview filtered dataset
filtered_df.head()

,Site_code,Latitude,Longitude,Country,Catchment_name,Galiza,Subsample,Calib_EFI_Medit,Calib_connect,Calib_hydrol,...,Squalius malacitanus,Squalius pyrenaicus,Squalius torgalensis,Thymallus thymallus,Tinca tinca,Zingel asper,Squalius sp,Barbatula sp,Phoxinus sp,Iberochondrostoma_sp
1,ES_02_0001,40.530188,-1.887796,Spain,Tejo,0,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
2,ES_02_0002,40.595432,-1.928079,Spain,Tejo,0,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
3,ES_02_0003,40.656184,-1.989831,Spain,Tejo,0,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
4,ES_02_0004,40.676402,-2.036274,Spain,Tejo,0,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
5,ES_02_0005,40.732830,-2.078003,Spain,Tejo,0,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
# Create filtered dataset using top 4 catchments
filtered_df = df[df['Catchment_name'].isin(top4)]

# Preview filtered dataset
filtered_df.head()

,Site_code,Latitude,Longitude,Country,Catchment_name,Galiza,Subsample,Calib_EFI_Medit,Calib_connect,Calib_hydrol,...,Squalius malacitanus,Squalius pyrenaicus,Squalius torgalensis,Thymallus thymallus,Tinca tinca,Zingel asper,Squalius sp,Barbatula sp,Phoxinus sp,Iberochondrostoma_sp
1,ES_02_0001,40.530188,-1.887796,Spain,Tejo,0,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
2,ES_02_0002,40.595432,-1.928079,Spain,Tejo,0,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
3,ES_02_0003,40.656184,-1.989831,Spain,Tejo,0,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
4,ES_02_0004,40.676402,-2.036274,Spain,Tejo,0,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
5,ES_02_0005,40.732830,-2.078003,Spain,Tejo,0,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0